### ISSUE TITLE
Extract unicode text

### ISSUE THREAD

**Issue by BjornFJohansson** [jorisschellekens/borb-examples#13]
Hi, I used borb to extract text from a PDF using SimpleTextExtraction in the example code below to learn how the tools works.
I did get the text out, but there seems to be unicode errors in the text, for example 

DossiÃª da Unidade Curricular 

instead of:

Dossiê da Unidade Curricular

Is there a way to add a codec somewhere?

```
#!chapter_005/src/snippet_005.py
import typing
from borb.pdf.document.document import Document
from borb.pdf.pdf import PDF
from borb.toolkit.text.simple_text_extraction import SimpleTextExtraction

def main():

    # read the Document
    doc: typing.Optional[Document] = None
    l: SimpleTextExtraction = SimpleTextExtraction()
    with open("output.pdf", "rb") as in_file_handle:
        doc = PDF.loads(in_file_handle, [l])

    # check whether we have read a Document
    assert doc is not None

    # print the text on the first Page
    print(l.get_text_for_page(0))


if __name__ == "__main__":
    main()
```

**Comment by jorisschellekens** [comment]
Hi,

You should not have to add a codec. PDF is a self-sufficient format.
Whenever a font is used in PDF there are (roughly) the following options:
- The font is one of the standard 14 fonts, and then the assumption is that the glyphs (the pixels on the page) are always mapped to unicode characters in the same way (using of 3 predefined codecs)
- The font, although not standard 14 makes use of one of the 3 predefined codecs. A font can still specify so called 'differences' where its glyphs and unicode do not match up.
- The font defines its own ToUnicode map. Every glyph has a glyph-id, and each glyph-id is mapped to a unicode character.

Can you attach the PDF you are using?
Then I can actually debug the issue and figure out what's going on.

Kind regards,
Joris Schellekens

**Comment by BjornFJohansson** [comment]
Thank you for your quick response. I send the file to you directly. Please let me know if you got it.

**Comment by BjornFJohansson** [comment]
Changing to:

`print(l.get_text_for_page(0)[:100].encode("ISO-8859-1").decode("utf8"))`

solved the problem. Seem that the text was decoded latin-1 and not utf8 as it is on my system.

**Comment by jorisschellekens** [comment]
So the problem boils down to this:

1. The content of a page is represented  by a content stream. This is a compressed string containing postfix operations.
2. Somewhere in your document, in the page content stream you have `(Dossiê ....) Tj`. Where `Tj` is the operator for drawing text and rounded brackets are used to denote strings.
3. When this command needs to be processed, I need to know which bytes are in the string, because I need to map each byte to a character using the encoding of the font that is being used for that text.

So it could be an encoding problem. In the current codebase, the string is decoded into bytes using utf8. I have now changed that to latin1, and I'm going to re-run the tests.

In particular I have one test that extracts text from a large collection of pdf documents, and compares the extracted text to what other software tools have extracted. Borb typically scores slightly less than 90% on that. Perhaps a change in encoding will get me over the 90%.

**Comment by jorisschellekens** [comment]
There does seem to be a slight improvement.
I'm going to investigate this a bit further.

**Comment by BjornFJohansson** [comment]
The pdf I sent you might not be up to spec. PyPDF (any version) fail to read the text at all.
So the problem could be on the side of the pdf generator.

**Comment by jorisschellekens** [comment]
Vera PDF is a website that allows you to easily verify whether a given pdf adheres to the standards.

https://demo.verapdf.org/

I tried that with your document, and this tool reported it was broken.

![image](https://user-images.githubusercontent.com/18642798/162500236-ffc66136-23ca-4bfd-ac53-41fea51f9638.png)


So I'm not surprised other readers refused to read it.
