### ISSUE TITLE
Issue while running snippets 002 from chapter 007

### ISSUE THREAD

**Issue by devanghingu** [jorisschellekens/borb-examples#14]
Hi I'm running python version 3.8 on top of ubuntu 18.04.
and ratting issue with snippets `#!chapter_007/src/snippet_002.py`  
getting error at  
```l: TableDetectionByLines = TableDetectionByLines()
    with open("data/ama_logistic_236523.pdf", "rb") as pdf_file_handle:
        doc = PDF.loads(pdf_file_handle, [l])

```
Error: `AssertionError: A Rectangle must have a non-negative width.`

when i try another PDF, first error passed and getting another error which mentioned below. 
```
# get page
    p: Page = doc.get_page(0)
```
Error: `TypeError: element indices must be integers`

**Comment by jorisschellekens** [comment]
Good morning,

This issue is not going to be easy to debug without your input document

Also, I noticed you work for Tntra. And the code you did post clearly mentions AMA Logistics.

It seems very clear to me that you are using this code in a commercial setting. And yet I don't have any record of a commercial license for Tntra or AMA Logistics.

Using `borb` in a commercial setting without a commercial license is not allowed unless your code is open source.

Get in touch with me (there is a "contact sales" in the readme, and on our website) for more details about buying a license.

Kind regards,
Joris Schellekens

**Comment by devanghingu** [comment]
Hi jorisschellekens,

Actually i was trying different different libraries for my problem and borb is one of them. Anyway I have found another library which suits my problem.

Thanks you.!
