### ISSUE TITLE
TextField Object filling the same answer in all textfields

### ISSUE THREAD

**Issue by StickySenior** [jorisschellekens/borb-examples#18]
I have been trying to use the code available in the chapter 4 about form fields. So, in the output PDF when I try to fill any TextField, the following Fields contain the same information. I would like to have them independent but that doesn't seem to work no matter how I try.

I am using borb version 2.0.27.

Does any know if the issue actually comes from the TextField Object or is it from something else ?

**Comment by almirodil23** [comment]
I have the same problem and I can't deal with it...hopefully someone can help

**Comment by jorisschellekens** [comment]
Should be solved in the latest release.

Also, in future please report bugs on the main repository.
This repository is meant to contain only the examples of the `borb` library.
A bug here would imply "this example does not work" rather than "the library does not work".

Kind regards,
Joris Schellekens
