### ISSUE TITLE
Support for non-english language

### ISSUE THREAD

**Issue by aminPial** [jorisschellekens/borb-examples#19]
`AssertionError: Font Helvetica can not represent '৳'`

I tried my custom font for the language "Bangla". But it doesn't work.

**Comment by jorisschellekens** [comment]
Hi there,

1. Please create bugs/issues/feature-requests in the main repository. This is the examples repository.
2. You are not using a custom `TrueTypeFont`. The error message makes it perfectly clear you are using Helvetica.
3. Not every font can represent every character. This is again made clear by the error. If you try to display a character that is not part of the font you are using `borb` will throw the aforementioned assert. As far as I am concerned, this is expected behaviour.

Kind regards,
Joris Schellekens

**Comment by aminPial** [comment]
Thanks for your kind reply. Please check here [borb failed to parse the font](https://ibb.co/wC1TqdC). Check the `Product Name, Unit Price and Total Price columns`. I am pretty sure the custom TTF I used does have all those fonts as I am already using that custom ttf on my website and they work just fine.

I have used my custom font like this:
`custom_font = TrueTypeFont.true_type_font_from_file(Path(__file__).parent / 'BanglaFont.ttf')
table_001.add(TableCell(Paragraph(i, font=custom_font)))
`
