### ISSUE TITLE
Long tables

### ISSUE THREAD

**Issue by evanti** [jorisschellekens/borb-examples#25]
Hi, what approach would you recommend to split long tables into multiple pages? I didn't find any built-in solution, but there must be a way, right?

**Comment by jorisschellekens** [comment]
Hi,

You're logging a ticket on the examples repository. That's not really applicable, since you claim there is missing functionality in `borb` it would make more sense to log this issue on the main repository. 

Also, in the main repository you'll find that there is a ticket on long tables (currently marked as solved) which comes with an example snippet.

Kind regards,
Joris Schellekens

**Comment by evanti** [comment]
Sorry, my bad.
