### ISSUE TITLE
Cant read an specif pdf file

### ISSUE THREAD

**Issue by warleygarcia2023** [jorisschellekens/borb-examples#33]
I have some trouble.
I'm getting the following message `Unexpected character at end of dictionary.` when trying to read this specifc pdf file.

**Comment by jorisschellekens** [comment]
Hi @warleygarcia2023,

If you had logged your issue on the main repository (rather than the examples repository), you could have selected one of the issue templates.

An issue template ensures I have all the information I need to be able to fix the bug.

For instance, in your case, it seems relevant to have the PDF in question.

There's a test in the main repository that reads a random selection of 10 (and also 100) PDF documents. The PDF documents I use for this can be found in one of my other repositories. These PDF documents have been "caught in the wild" so to speak.

So clearly `borb` is able to read PDF documents. But sometimes a PDF is "broken". This is non-technical speak for "The PDF does not adhere to the specification."

I am going to close this issue:
- you logged it on the wrong repository 
- you did not include code that allows me to reproduce the bug
- you did not include the input PDF

Please open a new issue on the main repository.

Kind regards,
Joris Schellekens

**Comment by warleygarcia2023** [comment]
i tried this code example

```python

#!chapter_005/src/snippet_005.py
import typing
from borb.pdf import Document
from borb.pdf import PDF
from borb.toolkit import SimpleTextExtraction


def main():

    # read the Document
    doc: typing.Optional[Document] = None
    l: SimpleTextExtraction = SimpleTextExtraction()
    with open("C:\\Users\\USUÁRIO\\FGTS\\guiateste.pdf", "rb") as in_file_handle:
        doc = PDF.loads(in_file_handle, [l])

    # check whether we have read a Document
    assert doc is not None

    # print the text on the first Page
    print(l.get_text()[0])


if __name__ == "__main__":
    main()
```

I attached the pdf file 
[guiateste.pdf](https://github.com/jorisschellekens/borb-examples/files/12196443/guiateste.pdf)

**Comment by jorisschellekens** [comment]
Can you test something (I'm pretty sure this is also going to cause the issue)

```python
import typing
from borb.pdf import Document
from borb.pdf import PDF


def main():

    # read the Document
    doc: typing.Optional[Document] = None
    with open("C:\\Users\\USUÁRIO\\FGTS\\guiateste.pdf", "rb") as in_file_handle:
        doc = PDF.loads(in_file_handle)

if __name__ == "__main__":
    main()
```

**Comment by warleygarcia2023** [comment]
the same code reads another pdf but not this one , i cant understand

**Comment by jorisschellekens** [comment]
The conclusion is fairly simple.
That particular PDF is (perhaps) broken. That's why `borb` doesn't want to read it.

**Comment by warleygarcia2023** [comment]
thank you

**Comment by jorisschellekens** [comment]
There's an online tool (Vera PDF checker), which will tell you whether a PDF adheres to the spec or not.

You can upload a PDF and it will give you a list of warnings/errors. Some are OK, and some are not.

https://demo.verapdf.org/
